### ISSUE TITLE
Inadequate Documentation

### ISSUE THREAD

**Issue by Zoher15** [OpenBioLink/SAFRAN#14]
I just finished installing SAFRAN using the documentation on a linux server but the instructions are not sufficient for the steps that should follow. The instructions say do the following for linux:
`./SAFRAN {action} {path_to_config}`

But what is path_to_config? Do we have to run AnyBURL to generate rules first? If so how do we pass them in the arguments?

**Comment by nomisto** [comment]
This is documented here https://safran.readthedocs.io/en/latest/manual/command_lines.html

> and `path_to_config` is a path to a file containing the configuration of an action as key-value pairs. Details to the configuration of a specific action can be seen on the [Actions page](https://safran.readthedocs.io/en/latest/manual/actions). The properties file should have the following format:
```
{KEY} = {VALUE}
{KEY} = {VALUE}
```

However this part "Details to the configuration of a specific action can be seen on the [Actions page](https://safran.readthedocs.io/en/latest/manual/actions)" is not valid anymore as I split the single actions page to multiple, see (Action applymax)[https://safran.readthedocs.io/en/latest/manual/applymax.html], (Action applynoisy)[https://safran.readthedocs.io/en/latest/manual/applynoisy.html], ....

So its a simple key value pair file, which PATH you pass as last argument.

**Comment by nomisto** [comment]
Closing this now, if you still have question, feel free to reopen it
