### ISSUE TITLE
What are the hyperparameters for reproducing KGE models for OpenBioLink

### ISSUE THREAD

**Issue by cosmeowpawlitan** [OpenBioLink/SAFRAN#2]
I had spent some time for searching table / details about hyperparameters (or candidate for grid search) or any other detailed configuration (about the use of true negative) for RESCAL or TransR model that achieve 0.615 and 0.592 hits@10 rate for OpenBioLInk, but I can't find any.

May I have same information about these values?

Thanks for you time.

**Comment by nomisto** [comment]
Hello @jerryIsHere,

I've added a table with the hyperparameters of the best models [here](https://github.com/OpenBioLink/OpenBioLink/blob/master/README.md#baseline-results) in the original OpenBioLink repo.

Thanks for pointing this out!
