### ISSUE TITLE
SAFRAN on Large Datasets

### ISSUE THREAD

**Issue by nikolaospanagiotou** [OpenBioLink/SAFRAN#4]
Dear authors,

I am facing some difficulties in running SAFRAN on a larger dataset. I have ~3M rules from AnyBURL. More specifically, I have a dataset of some millions of triples.
During the phase where the JaccardSimilarities are computed I faced the following two issues:

- For some rules, it was extremely time-consuming to generate all possible answers. It was running for days.
- After, adding an artificial timeout on very slow rules the calculation of the Jaccard similarities was very slow. It required one day in order to calculate the similarities for a single relation.

In terms of memory requirements, everything is fine. Less than 16GB are used. I would like to ask you if you have run SAFRAN on larger datasets that consist of tens of millions of rows. Have you run this implementation with any of the OpenBioLink databases mentioned in the ArXiv SAFRAN [publication](https://arxiv.org/pdf/2012.05750.pdf)?

**Note:** I faced some runtime exceptions on RuleReader.cpp. The solution was to replace **throws** of strings with instances of std::runtime_exception. Due to the permissions of the repository probably I am not allowed to create a pull request.
```
- throw "Id not found in nodeid's";
+ throw std::invalid_argument( "Id not in node ids" );
```

Thank you in advance for your time.

Kind regards,

**Comment by matthias-samwald** [comment]
@nomisto please check!

**Comment by nomisto** [comment]
Hello @nikolaospanagiotou ,

Sorry to hear that you are having troubles. We ran this implementation on the high quality directed OpenBioLink dataset (which contains about 4.5 million edges) where the runtime of the Jaccard calculation was about a few hours. We did however run it on a CPU with 96 threads, may I ask what processor you are using?

One thing you could also try is lowering the DISCRIMINATION_BOUND property, which in this context is the sample size for the calculation of the Jaccard. (I noticed that the documentation for this Property is wrong, rules which have solution sizes bigger than DISCRIMINATION_BOUND are not omitted, their solution size just can't get bigger than that)

I was not aware that we did set such a restriction, and honestly I cannot find such a setting. What was your workflow, if I may ask? (was it like [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork))

Cheers

**Comment by nomisto** [comment]
Another thing you could try is, to learn fewer rules and see if the performance changes much. AnyBURL usually achieves very good results with less rules and performance often stagnates or gets better only a little with more rules.

Furthermore, I was experimenting a little in the course of the last with a different implementation of the MinHash algorithm (which is used for estimating the Jaccard) and should be much faster. This implementation can be found at the `faster_jaccard` branch, is however untested. This also will need an installation of [OpenSSL](https://www.openssl.org/)

**Comment by nikolaospanagiotou** [comment]
Dear @nomisto many thanks for your rapid response. My dataset is larger than OpenBioLink, to be honest. In addition, the hardware I am using is less powerful than the one described above and I am using a very large amount of rules. Some of these rules have as expected a very low confidence.  

Is there a link to the rules used for the OpenBioLink experiment? I would like to see how many rules were used and some statistics about these rules.

Thanks in advance for your time.

**Comment by nomisto** [comment]
Of course, you can download the rules from [here](https://zenodo.org/record/5517166/files/obl-1000.zip), the total amount is about ~800,000.

Greetings

**Comment by nikolaospanagiotou** [comment]
Dear authors,

Many thanks for your rapid and also detailed feedback. Since this is probably an issue of my data and settings I am closing this issue and as you suggested I will experiment with a significantly smaller number of rules.

Kind regards,
