### ISSUE TITLE
Missing script for evaluating SAFRAN

### ISSUE THREAD

**Issue by Jean-KOUAGOU** [OpenBioLink/SAFRAN#7]
I was able to generate the prediction.txt file but I do not understand it. Morevover, I am unable to find link prediction results despite I specified the test.txt file in the configuration file and set EXPLAIN=1. Instead, I get a heavy explanation.db file which I doubt contains the link prediction results (in the format Hits@1, Hits@10, ...). Could you please help with the generation of link prediction results from the test.txt file?

**Comment by nomisto** [comment]
Hello @Jean-KOUAGOU ,

You are right explanation.db does not contain the link prediction result, it contains the explanations (Which rules caused which prediction; basically a more detailed version of the prediction.txt). Sorry for misleading you here!

I've included a script for evaluating SAFRAN now in the `python` folder (It was previously on another repository and not documented). Further I've added instructions how to use the script here: https://safran.readthedocs.io/en/latest/manual/evaluation.html and changed the documentation a little bit to avoid further misunderstanding.

For you that will be the "Evaluate a single prediction file" script and it should be run as

```bash
python eval.py {path to file containing predictions} {path to testset file}
```

f.e. with

```bash
python eval.py ./prediction.txt ./test.txt
```


Hope this helps!

**Comment by Jean-KOUAGOU** [comment]
Yes it helps. Let me download and try it. Thanks

**Comment by Jean-KOUAGOU** [comment]
You may also want to fix the indentation error in eval_experiment.py (the last part in if __name__=='__main__': print(dataset))

**Comment by Jean-KOUAGOU** [comment]
Finally, the reading mode "ansi" in eval.py and eval_experiment.py does not exist. I changed it to "ascii".

**Comment by nomisto** [comment]
Thanks reporting these bugs, I fixed them now.
