### ISSUE TITLE
Return index of best rule in apply_only_max

### ISSUE THREAD

**Issue by AVBelyy** [OpenBioLink/SAFRAN#8]
Hello!

I am trying to implement a feature that will return the index of the most confident rule that predicted a given entity: essentially turning this formula from the paper
```
score(e) = max{conf(f1), ..., conf(rk)}
```
into
```
bestrule(e) = argmax{conf(f1), ..., conf(rk)}
```
or, more concretely, `argtop_k`, to predict the 'best' rule for each of the top-K predicted entities.

How would advise to go about it? I understand that the `ScoreTree` structure is used to predict `score(e)` for all entities `e` at once, but I don't really understand how it works internally. Would it be possible to just store the rule ID inside each score tree node, and return it along with each entity and its score? For example, by modifying
```
ScoreTree::getResults(std::vector<std::pair<int, double>>& results)
```
into
```
ScoreTree::getResults(std::vector<std::tuple<int, int, double>>& results) // second element is the best rule's index
```
And then forwarding the results "upstream", all the way until `RuleApplication::writeTopKCandidates`?

**Comment by nomisto** [comment]
Hello!

You could look into [generating an explanation file](https://safran.readthedocs.io/en/latest/manual/expl.html) which creates a sqlite file containing all the rules that predict an entity. This would then be a very simple sql query to achieve this and I think this will save you from the hassle of implementing this. However this may be considerably slower and will depending on your knowledge graph create quite a big file. Let me know if you think that this won't work for you, then I'll look into the code.

**Comment by AVBelyy** [comment]
Yes, I think that addresses my problem!

Would it be possible to merge the `explanation` branch with the current master? (they diverged quite a bit, in that e.g. a `PREDICT_UNKNOWN` parameter is not supported in the `explanation` branch).  I'm actually working on Python bindings for SAFRAN (it's early stage, but seems to already support `applymax` and pass simple correctness tests) in a separate repository: https://github.com/AVBelyy/SAFRAN/tree/master/python_bindings. I would love to help provide a wrapper for the explanation function as well, bypassing the SQL layer if possible!

**Comment by nomisto** [comment]
Hello @AVBelyy , Sorry to get back to you so late, I've now managed to merge the explanation branch into the main. You trigger writing to an explanation file by setting `EXPLAIN = 1` in the config file. It is 0 by default.

Nice! I've been toying with the idea of writing bindings too, could however not find the time for that. Let me know if I can help you with anything!

**Comment by AVBelyy** [comment]
Thank you @nomisto, appreciate your work!  My understanding is, after running SAFRAN with `EXPLAIN = 1`, the explanations will be stored in the `Rule_Entity` table in the following format: for each prediction task with ID `TaskID`, and for each predicted entity (head or tail) with ID `EntityID`, we will store **all** the rules with ID `RuleID` that can predict the given entity in the task.  Is this understanding correct? And, in the context of `"applymax"` action, let's say for each `EntityID` I want to retain just the **single best** rule `RuleID` that predicts it. Would it be enough to join `Rule_Entity` and `Rule` tables and retain just the rule with the **highest `CONFIDENCE`** value?

**Comment by nomisto** [comment]
Yes, I think you got it right. Consider f.e. the triple `(h,r,t)` and you want to know which rules predicted `t` for the task `(h,r,?)`. `(h,r,?)` would correspond to `EntityID` and `RelationID` of the table `Task` (as well as the bool `IsHead` which determines if EntityID is a head entity, in this case `true`). The table `Rule_Entity` connects a `Task` (h,r,?) with all entities that got predicted and rule that predicted it.

So your SQL query would be something like that
```sql
SELECT * from Task 
	INNER JOIN Rule_Entity ON Task.ID = Rule_Entity.TaskID
	INNER JOIN Rule ON Rule_Entity.RuleID = Rule.ID
	WHERE Task.IsHead = 1 and Task.EntityID = 606 and Task.RelationID = 0 and Rule_Entity.EntityID = 2598
	ORDER BY Rule.CONFIDENCE DESC
	LIMIT 5
```

or if you don't know the internal ID of the entities/relations:

```sql
SELECT * from Task 
	INNER JOIN Rule_Entity ON Task.ID = Rule_Entity.TaskID
	INNER JOIN Rule ON Rule_Entity.RuleID = Rule.ID
	INNER JOIN Entity AS e1 ON Task.EntityID = e1.ID
	INNER JOIN Relation AS r ON Task.RelationID = r.ID
	INNER JOIN Entity AS e2 ON Rule_Entity.EntityID = e2.ID
	WHERE Task.IsHead = 1 and e1.NAME = "Houston_Rockets" and r.NAME = "isLocatedIn" and e2.NAME = "Texas"
	ORDER BY Rule.CONFIDENCE DESC
	LIMIT 5
```

Answer to both queries:

|ID|HEAD_CLUSTER_ID|TAIL_CLUSTER_ID|DEF|CONFIDENCE|PREDICTED|CORRECTLY_PREDICTED|
|--|--------------------|------------------|----|--------------|-----------|-------------------------|
|1171081|0|0|isLocatedIn(X,Texas) <= isLocatedIn(X,Houston)|0.5|22|11|
|1870989|0|0|isLocatedIn(X,Y) <= isLocatedIn(X,A), wasBornIn(B,A), isPoliticianOf(B,Y)|0.274271844660194|824|226|
|1521604|0|0|isLocatedIn(X,Y) <= isLocatedIn(X,A), diedIn(B,A), isPoliticianOf(B,Y)|0.266816143497758|892|238|
|2014529|0|0|isLocatedIn(X,Y) <= isLocatedIn(X,A), livesIn(B,A), isPoliticianOf(B,Y)|0.229116945107399|1257|288|
|1868457|0|0|isLocatedIn(X,Y) <= isLocatedIn(X,A), isLocatedIn(A,Y)|0.182543640897756|2005|366|

**Comment by AVBelyy** [comment]
Thank you! I want to make sure I understand the code as well. Let's consider the case of "applymax" action, where we predict the tail, so the `(h,p,?)` situation. First, we find all candidate tails `t`. Then, the `Rule_Entity` table is populated with *all the rules* that predict `t`, for each candidate `t` ([src](https://github.com/OpenBioLink/SAFRAN/blob/0f31bdfc66976beaf01680cf96a30e95f2b6e277/src/RuleApplication.cpp#L613)), using the `entityToRules[t]` mapping. The `entityToRules` mapping is initialized [here](https://github.com/OpenBioLink/SAFRAN/blob/0f31bdfc66976beaf01680cf96a30e95f2b6e277/src/RuleApplication.cpp#L516) and is reused between **multiple heads**. Shouldn't however `entityToRules` also depend on a **single head** in this situation? Consider the example of two different queries `(h,p,?)` and `(h',p,?)`. Both can predict the same tail `t`, but for **different** reasons (i.e., using different rules). However, the mapping `entityToRules[t]` is agnostic to the specific head and will clash both `h`-specific and `h'`-specific rules insides itself. Shouldn't `entityToRules` be thus defined (and used) locally, per each head separately? E.g. just below [the `for` loop that iterates over heads in a given HT bucket](https://github.com/OpenBioLink/SAFRAN/blob/0f31bdfc66976beaf01680cf96a30e95f2b6e277/src/RuleApplication.cpp#L517).

**Comment by nomisto** [comment]
No problem. You are right that `entityToRules` is defined outside of the for loop, however I think you are missing the `entityToRules.clear()` in L618. I am not sure anymore why I did that instead of declaring it inside the loop, but I think its a little faster to just clear it. Hope this resolves it.

**Comment by AVBelyy** [comment]
Ah I did indeed miss that, but it makes sense! And thanks again for clarifying how explanations work : I was able to get them to work in the bindings, will try to submit a PR soon :)
